### ISSUE TITLE
Problems to decode option 

### ISSUE THREAD

**Issue by TheDevKnight** [thoth-org/Thoth.Json#101]
HI, 

i use Thoth.Fetch 2.0.0 and have problem to decode the following type from json

```json
      {
        "Id": 2,
        "AccountId": 1,
        "Name": "5 Stck. MK8 Extruder Nozzle M6 für 1,75mm Filament RepRap MakerBot Ender 3",
        "SKU": "0236",
        "IsVariation": true,
        "VariationDetails": {
          "Case": "Some",
          "Fields": [
            "Durchmesser Düse 0,6mm"
          ]
        },
        "CreationDate": "2019-11-24T13:31:51Z",
        "Stock": 20,
        "Prices": [
          {
            "Id": 3,
            "ProductId": 2,
            "Value": 6.04,
            "Date": "2019-11-24T13:31:51"
          }
        ]
      },
```
here is the type definition

```fs
type Product =
    { Id: ProductId
      AccountId: AccountId
      Name: string
      SKU: string
      IsVariation: bool
      VariationDetails: string option
      CreationDate: DateTime
      Stock: int
      Prices: Price list } 
````

and here my decoder 

```fs
let productDecoder = 
    Decode.object (fun get ->
            { Id = get.Required.Field "Id" Decode.int
              AccountId = get.Required.Field "AccountId" Decode.int
              Name = get.Required.Field "Name" Decode.string
              SKU = get.Required.Field "SKU" Decode.string
              IsVariation = get.Required.Field "IsVariation" Decode.bool
              VariationDetails = get.Optional.Field "VariationDetails" Decode.string
              CreationDate = get.Required.Field "CreationDate" Decode.datetime
              Stock = get.Required.Field "Stock" Decode.int
              Prices = []
              //Prices = get.Required.Field "Prices" Decode.list<Price list> 
                                                                            })

let productEncoder (product:Product) = 
    Encode.object [
            "Id", Encode.int product.Id
            "AccountId", Encode.int product.AccountId
            // todo add missing fields 
        ]

let extraCoders =
    Extra.empty
    |> Extra.withDecimal
    |> Extra.withCustom productEncoder productDecoder
```

ive got the following error :( 

Error at: `$.[0].Products.[0].VariationDetails` Expecting a string but instead got: { "Case": "Some", "Fields": [ "Durchmesser Düse 0,6mm" ] }

What do i wrong?

**Comment by MangelMaxime** [comment]
Hello @TheDevKnight,

you are trying to decode a JSON generated by (I suppose) Newtonsoft.Net using Thoth.Json.

Thoth.Json and Newtonsoft.Net doesn't use the same representation for the types so they are not 100% compatible. 

I see 3 solutions:

1. Use Thoth.Json.Net on the server side as compatibility with Thoth.Json and Thoth.Json.Net is guaranted 
2. Customise Newtonsoft.Net to generate Thoth.Json compatible JSON
3. Create your own `Decode.newtonsoftOption` which support Newtonsoft.Net JSON

**Comment by TheDevKnight** [comment]
Hi @MangelMaxime,

thank you for the hint. I will try solution 1. and use Thoth.Json.Net in my .Net 5 BackEnd service. Do you have a sampler how to add Thigh.Json.Net to a .net Web API Project? 

Regards

**Comment by MangelMaxime** [comment]
Is this PR what you are looking for?

https://github.com/thoth-org/Thoth.Json.AspNetCore/pull/3

PS: Looks like I totally forgot to merge that PR and release a NuGet 😅

**Comment by TheDevKnight** [comment]
HI,

hmm i'm not sure, because its MVC and i use a .NET 5 Web API :/

For the moment i use a simple string property to get my code working. But strange was that the auto decoder can not map a null to string. Get the error that the decoder expected a string but get a null. 

1) Do i need a custom decoder to map null to a string? 

2) I found this issue (https://github.com/thoth-org/Thoth.Json/issues/57#issuecomment-653239823) where you post this code for .Net 

```
    let option (decoder : Decoder<'value>) : Decoder<'value option> =
        oneOf [
            fun value ->
                if Helpers.isNullValue value then Ok None
                else decoder value |> Result.map Some

            field "case" string
            |> andThen (
                function
                | "Some" ->
                    field "fields" (index 0 decoder) |> map Some
                | caseValue ->
                    fail ("`" + caseValue + "` is not a valid value for option<'T>")
            )
        ]
```
Is it possible to get this sample for Fable? 
How would a custom decoder look like to get the option type working with this sample?
```
type MyType = 
   { A : string
     B : string option }
```

Sorry for all these questions but im a bit frustated, because i want a clean shared model with options and currently i have placeholder like empty strings :(

Regards

**Comment by MangelMaxime** [comment]
> hmm i'm not sure, because its MVC and i use a .NET 5 Web API :/

You need to check how to replace default serializer to use Thoth.Json.Net.

Thoth.Json consider `null` as not a valid string representation.

If the string can have "non string" representation then it consider that you should map it to `string option`.

In current version of Thoth.Json I don't think you caneasily override the option decoder. It is coming in the next major version.

You will need to use Manual decoder instead of Auto decoders to have a finer control.

> Is it possible to get this sample for Fable?

Well, for Fable it would be the same code... you just need to copy the `Helpers` module because it is marked as internal in Thoth.Json https://github.com/thoth-org/Thoth.Json/blob/4fa03aef71d676c906a88620c86ac390d2c0c53f/src/Decode.fs#L12-L31

*It is possible that you need to force clear your cache*
[Fable REPL 2](https://fable.io/repl2/#?code=PYBwpgdgBAKgFsALnAdAKQM7AgKFJKAMQEMAjAGzBQGFgAnKzASQkTDtD3GhIqtoY4cAemFRaIAJZgAJlABmHALawEydFmgBjYDLA4lugK6Uok1uwjFyUABJhy4OhigBeHFE9RKiMxHLmYGYYAHIm5ABq1kZBABTAAFxQmNhR5DEAlEmkwMA2rsFh5DbAQoYyJkEAImA6em5CXt5gvhBgAO6I2FjyiADKiACelADyIIiS2FCxenXsUEk1c3QAPADkAG7RYAB8GQtQS7rs61vpQaAT2DsNTU1HeijYYCPyUADaHnff8kbQIMRkFAzjEoABaHZfb7QsxveyOdgYFCSULhNKgkFBZAEKEwvEjADWUBCz1xeK8DgwQTJ5Lus2OdCgAKBmKgAB8bgAlMAYEyIFBKYggKB9YBKfQ074PKjyaTkOQAIi0xCpCsOtWOKAwiDo5gA5pK7hz1XMUMQIDJ4ARYoaYb8IForrhaUaoArReK1RDbbTpShZQ5FQH5Rg1bE-eY9AAPKAABig9L0dH2xr9guFHv0LqabKgyqp6KC3uz0L98mIkhssQVAAM1QBqPMqsCFqCN2vBKAQJBQYjA6ySOSs+T0KCXSYQdYwHYKjI+zxzmEAXTKxlMAFEHccGrifF2Ol0ID1+kNRuMJ9NIMsDms+xDkppC-t3Ha-o6J4bc5n++dwZCXZuprAKQABWtS+J8JaeEqzYKgANFAgGatquoQHqbqZgq853AqwYyKGCFIY8xB0HQxCDB8bLYTCV4Mj+MTUV4bIri6K6fsSzx-thRFUMBYGOh8jHQfmYDwYhW6PCh+oYWKolCW6eEEeJpokWRFHvFRUF3DxKAQJW8nMdhK6iLAPKIBgQhDOAUAALKDDAgzWQUuIAN5QIaACCBxSWhhoAELeTq0njlMuIAL6NF42qApIWhQOKSikPMPGMrEGxJHZDngM+ho6Xx4GCS6CoeWJOk+ehGwoB52EKn5pUSVQbSdN0wC9AMwwvOeUxlUFaHAigfmGmxTTRRMcUJUljLSoyL6lhqjz5QJsT2lAeotFxLoufJXkFGt-LcgAjkYkgMDIKCEHKiolSayG9QaWkBbtLQoIdx2nedl1unV0x+k1h7Hu1Z5Ojdkl3YutIRTCc44HuGwAIxuO5TRbTCO1ugAChwThDFAJX+Yj34Kpj+B0DjdXhUIe4gZoCOzZ4OldAMqHoQALNMmWOVQKXAnD0NoH0KA6EeeRUOQwB6rE1PYLzlPrYmsiFrTSNeH6fwYMQ8hgIQyhM9JHPgCg01QFLEBw0I-OCy1lAoGLEvldM8syIriPwxk0OwwATIjrmeYjRNY+wON4zCj0cW0FMw+tJte3Tymaozd1QGzsT61zDWMhsHt8wLQtYNbtuS5oWey74juFjHyueKrR4a1rOuJ6nhvzfM0fmznVui+LsT2zMzdO9sFeZ27QA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q)

> How would a custom decoder look like to get the option type working with this sample?
> 
> ```fsharp
> type MyType = 
>    { A : string
>      B : string option }
> ```

Sorry but you will have to provide the expected JSON representation in order for me to help you. Because, right now Thoth.Json is fully capable of handling this type on it's own. It's just doesn't use the JSON representation you are expected/used too.

Even if it is possible to customize Thoth.Json to support Newtonsoft it is not the safest road. Personnally, I encourage you to check how to hook Thoth.Json into your server because you will be able to share much more code and also have safer JSON manipulation.

**Comment by TheDevKnight** [comment]
HI @MangelMaxime,

i test the code from https://github.com/thoth-org/Thoth.Json.AspNetCore/pull/3 
Must update the .net sdk to 3.1.xx to build it. 
But it has no effect on my service, inject it like newtonsoft 

`services.AddControllers().AddThothJson(fun options -> ()) |> ignore ` 
and test also the IsCamelCase 
`services.AddControllers().AddThothJson(fun options -> options.IsCamelCase <- true) |> ignore ` 

but nothing happends. The result of the serialization looks like the normal default of System.Test.Json 

Some case
```
"Variation": {
          "Value": "25mm"
        }, 
```
None case
```
"Variation": null, 
```

I don't know why it is not working because my app compile, build and run. 
I had problems with the camelCase because i want PascalCase so i updated the Thoth.Json.AspNetCore to use Thoth.Json 4.1.0 and use CaseStrategy in the ThothJsonResultExecutor.fs
But no effect :(

So i switch to the solution in my webapp and use your code for the newtonsoftStyle to get the style of System.Text.Json to work. Because i dont need newtonsoft in my backend. Don't know why it was used, maybe a old project template or copy&paste error of me :)

```
open Thoth.Json
open Fable.Core.JsInterop
open Fable.Core

let inline isNullValue (o: JsonValue): bool = isNull o

let encodeOption (encoder : 'a -> JsonValue) =
        function
        | Some value ->
            Encode.object [
                "Value", Encode.string value
            ]
        | None ->
            Encode.nil

let decodeOption (decoder : Decoder<'value>) : Decoder<'value option> =
        Decode.oneOf [
            fun path value ->
                if isNullValue value then 
                    Ok None
                else 
                    decoder path value |> Result.map Some

            Decode.field "Value"  decoder |> Decode.map Some
        ]
```
I now use a manuel encoder/decoder for my types and everything works! 👍 

BUT hopefully one last question...

Is it possible to combine manuel and auto encoder/decoder?

```
let encodePrice (price:Domain.Price) = 
    Encode.object [
            "Id", Encode.int price.Id
            "ProductId", Encode.int price.ProductId
            "Value", Encode.decimal price.Value
            "Date", Encode.datetime price.Date
        ]

let decodePrice = 
    Decode.object (fun get ->
            { Id = get.Required.Field "Id" Decode.int
              ProductId = get.Required.Field "ProductId" Decode.int
              Value = get.Required.Field "Value" Decode.decimal
              Date = get.Required.Field "Date" Decode.datetime }:Domain.Price)

let encodeProduct (product:Domain.Product) = 
    Encode.object [
            "Id", Encode.int product.Id
            "AccountId", Encode.int product.AccountId
            "Name", Encode.string product.Name
            "SKU", Encode.string product.SKU
            "Variation", encodeOption Encode.string product.Variation
            "CreationDate", Encode.datetime product.CreationDate
            "Stock", Encode.int product.Stock
            "Prices", Encode.list <| List.map encodePrice product.Prices // possible to switch to auto encoder?
        ]

let decodeProduct = 
    Decode.object (fun get ->
            { Id = get.Required.Field "Id" Decode.int
              AccountId = get.Required.Field "AccountId" Decode.int
              Name = get.Required.Field "Name" Decode.string
              SKU = get.Required.Field "SKU" Decode.string 
              Variation = get.Required.Field "Variation" (decodeOption Decode.string)
              CreationDate = get.Required.Field "CreationDate" Decode.datetime
              Stock = get.Required.Field "Stock" Decode.int
              Prices = get.Required.Field "Prices" (Decode.list decodePrice) // possible to switch to auto decoder?
              }:Domain.Product)

let extraCoders = 
    Extra.empty
    |> Extra.withDecimal
    |> Extra.withCustom encodeProduct decodeProduct
    
```
Because i need only the manuell encoder/decoder for the product type with the option and not the price.
But the price is nested as list in the product type. 

Regards

**Comment by MangelMaxime** [comment]
> Maybe you could update/fix the Thoth.Json.AspNetCore after the integration of the PR

Unfortunately, I never used AspNetCore so I don't think I can be of much help or would have to invest more time that I have available here.

> Is it possible to combine manuel and auto encoder/decoder?

Yes it is possible.

You can use `Decode.Auto.generateEncoder` or `Decode.Auto.generateEncoderCached` [documentation about caching here](https://thoth-org.github.io/Thoth.Json/#Caching) in order to get back an `encoder` or `decoder` which are compatible with the manual one.

**Comment by MangelMaxime** [comment]
I am closing this issue because the original problem is not coming from Thoth.Json library. But feel free to comment if more support is needed etc.

**Comment by TheDevKnight** [comment]
Hi @MangelMaxime, 

the missing support auf AspNetCore is not so bad because i found a good solution - from my point of view :) 
Thx for the hint with the auto encode/decoder. Works perfect! 👍 

Regards
