### ISSUE TITLE
Question: type-safe, exception-free ad-hoc access?

### ISSUE THREAD

**Issue by njlr** [thoth-org/Thoth.Json#111]
Suppose I have a blob of JSON like this:

```json
{
  "items": [
    { 
      "id": "f909a83c-bc73-4ec4-96da-6bef247ec688",
      "name": "apple"
    },
    { 
      "id": "9137ee0d-0a54-49b0-b64e-34427abcb727",
      "name": "banana"
    }
  ]
}
```

I want to get the `id` of the first element. I don't want to write a library of decoders, since this is a one-off. Ideally the solution is a one-liner. 

In an unsafe way, I could do this in JS like so:

```javascript
const firstId = JSON.parse(data).items[0].id;
```

I would like to achieve something similar in F#, but with more safety:

```fsharp
let firstId : Result<Guid, string> = // something
```

What I have come up with: 

```fsharp
let firstId = Decode.fromString (Decode.field "items" (Decode.first (Decode.field "id" Decode.guid))) data
```

The F# solution is more robust, but I think the JS version is more readable. 

Is there a suggested way with Thoth to perform ad-hoc field access that _reads like_ the JS version, but with the safety of the F# version?

**Comment by MangelMaxime** [comment]
Hello @njlr,

well the solution seems ok.

I guess `Decode.first` is a custom decoder if you don't want to create it you can use `Decode.index 0 decoder`.

I think in the past Thoth.Json was more permissive when using `Decode.at` allowing you to write things like:

```fs
Decode.at [ "items"; "0"; "id" ] Decode.guid
```

but nowadays it seems like I made it more strict (safe?) because it doesn't consider `array` as an object.

If you prefer this version, you need to made Decode.at

https://github.com/thoth-org/Thoth.Json/blob/78ea91a73fa4d3587118e040eed92a7f61b1eb06/src/Decode.fs#L379-L402

less strict especially this line

https://github.com/thoth-org/Thoth.Json/blob/78ea91a73fa4d3587118e040eed92a7f61b1eb06/src/Decode.fs#L389

The only way, to have a code looking similar to JavaScript is by using `Item` extension but I don't think this is possible to abuse it like that in this case.

By "item extension" I mean stuff like that:

```fs
// Taken from Fable.Core.DynamicExtensions
type Object with
      [<Emit("$0[$1]{{=$2}}")>]
      member __.Item with get(idx: string): obj = jsNative
                     and set(idx: string) (value: obj): unit = jsNative

// This allow any object to have this syntax:
foo.["b"]
```

![image](https://user-images.githubusercontent.com/4760796/124760088-aaafbc00-df30-11eb-9489-1ac4fbeeb745.png)

[Source](https://fable.io/docs/communicate/js-from-fable.html#Dynamic-casting)

**Comment by njlr** [comment]
Another solution. I like how this is still strict. Perhaps not quite as nice as the JS though. 

```fsharp
#r "nuget: Thoth.Json.Net"

open Thoth.Json.Net

let json = """{
  "items": [
    {
      "id": "f909a83c-bc73-4ec4-96da-6bef247ec688",
      "name": "apple"
    },
    {
      "id": "9137ee0d-0a54-49b0-b64e-34427abcb727",
      "name": "banana"
    }
  ]
}
"""

// high precedence, right associative backward pipe
// See: https://stackoverflow.com/a/21093613/1256041
let inline (^<|) f a = f a

let firstID =
  json
  |> Decode.fromString
    (
      Decode.field "items"
      ^<| Decode.index 0
      ^<| Decode.field "id"
      ^<| Decode.guid
    )

printfn "%A" firstID
// Ok f909a83c-bc73-4ec4-96da-6bef247ec688

```

**Comment by MangelMaxime** [comment]
Ah yes, didn't think about custom operators.

I suppose it depends on your personal preference.

I am closing this issue because I don't think their is much that can be done from this repo perspective.
