### ISSUE TITLE
The module/namespace 'Encode' from compilation unit 'Thoth.Json' did not contain the val 'ValLinkagePartialKey(toString)'

### ISSUE THREAD

**Issue by JintaoXIAO** [thoth-org/Thoth.Json#135]
hi team, 
I am a .net && f# new bee(have java background)
Just encountered the same error as [ValLinkagePartialKey(generateEncoder) #45](https://github.com/thoth-org/Thoth.Json/issues/45), 
the sample project is `SAFE-Chat`, I just fork it and upgrade to netcore3.1 and do `paket update`. please help on this or just close it if I put it in the wrong place. :)

please refer:
 [SAFE-Chat](https://github.com/JintaoXIAO/SAFE-Chat)

reproduce step:
`dotnet build src/Client/client.fsproj`

**Comment by MangelMaxime** [comment]
Hello @JintaoXIAO,

can you please make sure that you are using the last version of all the libraries that use Thoth.Json ?

I am asking that because oftem it is caused by not using the latest version of the different libraries. If that's not the case, we need to identify which library has not been updated yet to it.

Sorry for the problem encountered, this is .NET doing weird stuff and not explaining the real error source...

**Comment by JintaoXIAO** [comment]
thanks, @MangelMaxime,
yes got your point, I find that there is a dependency `Fable.Websockets.Client` (from `Fable.Websockets`) has a dependency on this package (`>=3.2`), and `Fable.Websockets` was the last released at 2019, I guess that' the problem, and I'll investigate on that. 
Just close it. :)
