### ISSUE TITLE
Nitpick: Change "I found the following" text

### ISSUE THREAD

**Issue by forki** [thoth-org/Thoth.Json#19]
In general I think we should not treat tools as persons. Consider to change the message to "The following errors were found:"

**Comment by MangelMaxime** [comment]
If someone wants to work on this issue here are the steps to follow.

1. Change the error messages at [this place](https://github.com/thoth-org/Thoth.Json/blob/master/src/Decode.fs#L83-L86).

- `I run into the following problems:\n\n` to something like `The following errors were found:\n\n`
- `I run into a `fail` decoder: ` to something like `A `fail` decoder has been reached: `

2. Run the tests `./fake.sh build -t MochaTest` or `./fake.cmd build -t MochaTest` and update the failing tests to the new naming

**Comment by MangelMaxime** [comment]
Released in 3.3.0
