### ISSUE TITLE
Bypassing internal JSON parsing

### ISSUE THREAD

**Issue by laurentpayot** [thoth-org/Thoth.Json#196]
Hi, I’m using a web worker to transmit JS objects (`MessageEvent.data`) to Fable. Thanks to the [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), these objects should be the same as if they were the result of a successful `JSON.parse()` operation (no functions, etc.).
But to leverage all the great Thoth.Json features (structure validation, getting F# types), I have first to convert my JS object to a JSON string, then use `Decode.fromString` that will [internally convert the JSON string back to a JS object](https://github.com/thoth-org/Thoth.Json/blob/b5777a9034f9b6a9c2010c7392b51d1f534fda93/packages/Thoth.Json.JavaScript/Decode.fs#L70).

Is there a way I could avoid these unneeded JS to JSON + JSON to JS transformations?
Could something like a `Decode.fromObj` be conceivable?

**Comment by MangelMaxime** [comment]
Hello @laurentpayot ,

Which version of the library are you using Thoth.Json (legacy) or Thoth.Json.JavaScript?

If this is is the former, I think you are looking for `Decode.fromValue` which is what is used by `Decode.fromString`.

If this is the later, I need to expose it because I forgot about it 🫣

Is is the API you are looking for ?

**Comment by laurentpayot** [comment]
Hello @MangelMaxime,

I am using Fable with Thoth.Json because Thoth.Json.JavaScript is not mentioned in the [docs](https://thoth-org.github.io/Thoth.Json/documentation/concept/fable-and-dotnet-support.html) and I was not aware of its existence :wink:  

Yes it looks like `Decode.fromValue` does exactly what I need, i.e. the same as `Decode.fromString` but without the parsing. Thanks! :+1: I will try to use it ASAP to see if it works. Could you expose it in Thoth.Json.JavaScript so I’m not using a legacy library? :pray:

The other way around, is there a function in the `Encode` module that bypasses `JSON.stringify()` and simply returns a plain JavaScript object?

**Comment by MangelMaxime** [comment]
> I am using Fable with Thoth.Json because Thoth.Json.JavaScript is not mentioned in the [docs](https://thoth-org.github.io/Thoth.Json/documentation/concept/fable-and-dotnet-support.html) and I was not aware of its existence 😉

Yes i am working on the documentation. Was blocked because I rewrote Nacara to use Eleventy but making progress on that.

The API is more or less the same as before with the deference where `Thoth.Json.Core` host the cross platform API and then each platform / library have their own package like Thoth.Json.Newtonsoft, Thoth.Json.JavaScript.

This removes the needs for compiler directives when working on shared libraries for cross-platform projects.

> The other way around, is there a function in the `Encode` module that bypasses `JSON.stringify()` and simply returns a plain JavaScript object?

In theory, the object that you pass to `Encode.toString` is already what you are looking for we don't need anything special in this case.

**Comment by njlr** [comment]
For the _legacy_ version, perhaps something like this?

```fsharp
#r "nuget: Thoth.Json, 10"

open Thoth.Json

// Domain type
type MessageEvent =
  {
    Foo : int
  }

// Encoders and decoders
module MessageEvent =

  let encode : Encoder<MessageEvent> =
    fun x ->
      Encode.object
        [
          "foo", Encode.int x.Foo
        ]

  let decode : Decoder<MessageEvent> =
    Decode.field "foo" Decode.int
    |> Decode.map (fun foo -> { Foo = foo })

// To create a plain JavaScript object, use the encoder
let messageEventToRawData (ev : MessageEvent) : obj = 
  MessageEvent.encode ev

// To decode a plain JavaScript object, use Decode.fromValue
let processRawMessageEvent (data : obj) =
  let decoding =
    data
    |> Decode.fromValue "$" MessageEvent.decode

  match decoding with
  | Ok ev ->
    printfn $"%A{ev}"
  | Error message ->
    printfn $"Error: %s{message}"
```

**Comment by laurentpayot** [comment]
By the way, I’m waiting to test this on my app before closing this issue.

Do you want me to open another issue regarding the missing `Decode.fromValue` in Thoth.Json.JavaScript?

**Comment by MangelMaxime** [comment]
> Do you want me to open another issue regarding the missing `Decode.fromValue` in Thoth.Json.JavaScript?

No that's fine keeping it here.

I am working on adding it right now. In reality, it is already exposed but as a low level API. So you could already use it, but you will be block with the `Encode` version of it because the published version doesn't manipulate an `obj` directly but instead use an intermediate DUs. This is already changed thanks to @njlr but I discovered today that I forgot to make a release.

I probably got side tracked by another project like Fable / Glutinum / EasyBuild 🫣. I will make sure to make as soon as I possible.

**Comment by laurentpayot** [comment]
Just confirming that `Decode.fromValue` of Thoth.Json (legacy) is working great on my app.

Any news from the missing `Decode.fromValue` in Thoth.Json.JavaScript? No pressure, but what would be the benefits of using Thoth.Json.JavaScript instead of Thoth.Json?

**Comment by laurentpayot** [comment]
@MangelMaxime 

On my POC SPA (pure client), I made a `dotnet paket remove Thoth.Json` then `dotnet paket add Thoth.Json.JavaScript` 

In a file I `open Thoth.Json.Core` to use `Decode.object`. **No compiler error**, but at runtime I get (for this file):
```
Uncaught ReferenceError: Thoth_Json_Core_Decode_object is not defined
```

Did I do something wrong?

**Comment by MangelMaxime** [comment]
@laurentpayot This doesn't ring a bell to me.

You could try to add `Thoth.Json.Core` explicitly too but this is strange because if you have access to the API in your IDE then the package is installed too.

Is your project public? If not, you could try to reach to me on the F# discord / F# slack to have a look at it together.

**Comment by joprice** [comment]
I hit the same issue [here](https://github.com/thoth-org/Thoth.Json/issues/204). I ended up publishing a fresh version to my privage github packages nuget repo and have been relying on that since.

**Comment by MangelMaxime** [comment]
@laurentpayot I re-packaged the libraries there was an error in the published version.

If you run `dotnet paket update` in your project it should works now. I am closing this issue, because I think the orignal problem is solved. Feel free to re-open if needed.

**Comment by laurentpayot** [comment]
I can confirm Thoth.Json.JavaScript is working now both in my POC SPA and in my example repo. Thanks a lot @MangelMaxime! :+1:
