### ISSUE TITLE
Object should have prototype to decode

### ISSUE THREAD

**Issue by nojaf** [thoth-org/Thoth.Json#23]
Hi, I'm having a bit of a strange thing here.

```fsharp
open Fable.Core
open Fable.Core.JsInterop
open Thoth.Json

let decoder : Decoder<int> = Decode.object (fun get -> get.Required.Field "a" Decode.int)

let foo = createObj ["a" ==> 42]

Decode.fromValue "$" decoder foo
|> printfn "Decoded foo %A"

// I don't do this myself but due to interopt I've noticed my object has no prototype anymore.
let fooWithout = JS.Object.setPrototypeOf(foo, null)

Decode.fromValue "$" decoder fooWithout
|> printfn "Decoded foo without %A"
```

The result of this is
```

Decoded foo Ok 42
Decoded foo without Error Error at: `$`
Expecting an object but instead got:
{
    "a": 42
}
```
Any ideas?

**Comment by MangelMaxime** [comment]
Hello,

the way we are detecting an object is as follows:

```fs
[<Emit("$0 === null ? false : (Object.getPrototypeOf($0 || false) === Object.prototype)")>]
let isObject (_ : JsonValue) : bool = jsNative
```

[Source](https://github.com/thoth-org/Thoth.Json/blob/master/src/Decode.fs#L27-L28)

So because you are removing the prototype then the `isObject` helpers return false. If you know a better/another way to detect object I am open to ideas.

**Comment by nojaf** [comment]
Well, unfortunately, some library is doing this so it is not under my control.
Thanks for confirming my theory here, I was slightly going mad why it didn't decode this.

I'll think about another way of detecting this if don't come up with something then I propose we just document it.

**Comment by MangelMaxime** [comment]
If you end up, working a lot with object that don't have prototype, you could create `Decode.NoPrototype.object`, `Decode.NoPrototype.get` helpers.

Those helpers would have mostly the same code as the original ones, but with a more permissive `isObject` check. Of course, this means that if you apply those new helpers against a primitive type like `int` the error message will be slightly off. 

Instead of saying something like: `Expecting an object but got: 10`, you will probably have the `Expecting an object with a field 'Foo' but got: 10`.

**Comment by nojaf** [comment]
That would be fine actually, how would those decoders look like?

**Comment by MangelMaxime** [comment]
Hum 🤔, while writing this answer I discovered it would be a bit more work than planned because I don't expose the `Helpers` module...

1. Create a `module Decode.NoPrototype`

2. Copy the [`Helpers`](https://github.com/thoth-org/Thoth.Json/blob/master/src/Decode.fs#L11-L52) module

    Then, change the `isObject` into a more permissive check.

    For example:
    ```fs
    // Original version
    [<Emit("$0 === null ? false : (Object.getPrototypeOf($0 || false) === Object.prototype)")>]
    let isObject (_ : JsonValue) : bool = jsNative

    // Much more permissive version
    [<Emit("$0 === null")>]
    let isObject (_ : JsonValue) : bool = jsNative
    ```

3. Then copy/paste the code of theses decoders:

- `field`
- `at`
- `optional`
- `optionalAt`

4. Then copy/paste the `object` builder, code [Source](https://github.com/thoth-org/Thoth.Json/blob/master/src/Decode.fs#L601-L671) by making use your custom version of the previously listed decoders.

In theory, those are the big steps to follow.

If I can give an advice, I would still use the orignal decoders when possible and only use `Decode.NoPrototype` where it's needed.

**Comment by nojaf** [comment]
Hmm, I think I set my prototype again using

```fsharp
let o = createEmpty<obj>
let objProto = JS.Object.getPrototypeOf(o)
let fooWithAgain = JS.Object.setPrototypeOf(fooWithout, objProto)

Decode.fromValue "$" decoder fooWithAgain
|> printfn "Decoded foo without %A"
```

This works so maybe that can be my workaround.
Copy pasting parts of the helper module can get out of sync so that is not ideal.

**Comment by MangelMaxime** [comment]
> This works so maybe that can be my workaround.

It can indeed be a simpler solution. And could be added as a simple helper `myValue |> ensurePrototype`

> Copy pasting parts of the helper module can get out of sync so that is not ideal.

Indeed, in theory, the next major version of Thoth.Json will expose those helpers.
