### ISSUE TITLE
skipNullField equivalent for decoder? (Use default values)

### ISSUE THREAD

**Issue by stroborobo** [thoth-org/Thoth.Json#44]
Auto encoding with skipNullField produces JSON which seems to be incompatible to the auto decoder. Is there a way to make Thoth use some default values if a field is not found? Or maybe just enabling to accept null/undefined for strings?

**Comment by MangelMaxime** [comment]
`null` is not a valid value for `string` that's why it's failing in your case.

If a string can have "no value" you can use `string option` and the decoder should be happy with that.

If I start to accept `null` for `string`, I would probably have to accept `null` for any types (int, byte, etc.), and hurt the type safety of Thoth.Json.

**Comment by stroborobo** [comment]
Technically null is a valid for string, it's not for the primitive value types. If you want to keep it explicit, that's alright. Thank you for your thoughts :)
