### ISSUE TITLE
Snake case?

### ISSUE THREAD

**Issue by adz** [thoth-org/Thoth.Json#47]
I'd like to support "snake_case", which our API uses (generally Ruby/Elixir apps follow this convention).

I can see it is implemented here:
https://github.com/thoth-org/Thoth.Json/blob/master/src/Decode.fs#L1053

and here for encoding:
https://github.com/thoth-org/Thoth.Json/blob/master/src/Encode.fs#L396

Otherwise it's just passed around a lot.

I started on it, and can make a PR where the "isCamelCase" is changed to "caseStrategy" and change it in to a union type... or it could be another flag `isSnakeCase` but seems clunky, and also open to weirdness (both could be set). 

The first idea could work and still be compatible by allowing both `isCamelCase` and  `caseStrategy` in the entry point functions `Decode.Auto.fromString` and similar which then normalises .

What are your thoughts, and would you accept any such PRs for this feature?

**Comment by MangelMaxime** [comment]
Hello @adz,

I am ok to support snake case (it has been mentionned several time to me).

I prefer to change`isCamelCase ` to ` caseStrategy` via an union type. It feels more robust and less easy to mess up from the user point of view.

Adding this new options, will result in a new major release because we are changing the API but it's a small change so people should not have a hard time upgrading their code.

**Comment by adz** [comment]
Great thanks. We ended up doing manual encoding which wasn't too much for us, and feels similar from our Elm code.

I'll still work on this during the week.

**Comment by adz** [comment]
@MangelMaxime - I have submitted a PR for this now - do you have any comments? I'll only ping this once to avoid being too annoying. thanks for your time!
