### ISSUE TITLE
Units of measure with decimal can't deserialize on client

### ISSUE THREAD

**Issue by AkosLukacs** [thoth-org/Thoth.Json#48]
Deserialization of decimal<UnitOfMeasure> doesn't work on the client.

```
[<Measure>] type Foo
type Counter = { Value : decimal<Foo> }
```
Fails with `Cannot generate auto decoder for Microsoft.FSharp.Core.decimal'1. Please pass an extra decoder.`
It does work if the "type" is int or float instead of decimal.

Sample repo based on safe template: https://github.com/AkosLukacs/UnitOfMeasureThoth

Fun fact: it did work in the other direction: I use Fable.Remoting. Set a value on the client, sent it to server, saved to db without an issue. It only blew up when the client tried to deserialize.
Since UoM is erased, only the number is sent across as JSON.
[Reported in the SimpleJson repo too](https://github.com/Zaid-Ajaj/Fable.SimpleJson/issues/41), might be a default F# behaviour?

**Comment by MangelMaxime** [comment]
Units of measure are indeed only existing at compilation time, when executed on the runtime there is no information about them.

The problem you are facing here, is that we decided to not support `decimal` type out of the box in Thoth.Json because it was increasing the bundle size "a lot" and not everyone is using them.

So you should just provide `decimal` support via the extra coder mechanism (by using `Extra.withDecimal`).

[Source code](https://github.com/thoth-org/Thoth.Json/blob/master/src/Encode.fs#L531-L541)

**Comment by MangelMaxime** [comment]
I am closing this issue, feel free to re-open if needed.
