### ISSUE TITLE
Deserialization and JSON Path

### ISSUE THREAD

**Issue by gsscoder** [thoth-org/Thoth.Json#51]
First of all, thank you for excellent work. Evaluating various libs, your seems the more clean!
I've defined these type (just few fields):
```fsharp
type StockQuote = {
        symbol : string
        profile : Profile
    } and Profile = {
        price : float
    }
```
to parse:
```json
{
  "symbol" : "ORCL",
  "profile" : {
    "price" : 52.98,
    "beta" : "1.085241",
    "volAvg" : "17954506",
    "mktCap" : "192529320000.00",
    "lastDiv" : "0.96",
    "range" : "42.4-54.65",
    "changes" : 0.0,
    "changesPercentage" : "(0.00%)",
    "companyName" : "Oracle Corporation",
    "exchange" : "New York Stock Exchange",
    "industry" : "Application Software",
    "website" : "http://www.oracle.com",
    "description" : "Oracle Corp is a computer software company. It sells enterprise information technology solutions, including databases, middleware, applications, and hardware. The Company primarily offers software licenses, support, and maintenance services worldwide.",
    "ceo" : "Mark V. Hurd / Safra Ada Catz",
    "sector" : "Technology",
    "image" : "https://financialmodelingprep.com/images-New-jpg/ORCL.jpg"
  }
}
```
This perfectly works with:
```fsharp
Decode.Auto.fromString<StockQuote>(resp);;
```
But if I want to target a type like this (non recursive):
```fsharp
type StockQuote = {
        symbol : string
        price: float
} with
  static member Decoder : Decoder<StockQuote> =
           Decode.object
               (fun get -> {
                    symbol = get.Required.Field "symbol" Decode.string
                    price = get.RequiredField "$.profile.price" Decode.float
                    })
```
I got an error using:
```fsharp
Decode.fromString StockQuote.Decoder jsonstring
```
What's the correct way to access nested fields?

Thank you

**Comment by MangelMaxime** [comment]
Hello,
thank you for the kind words :)

In order to decode a path you should use `get.Required.At`. It take a list, which contains the differents nodes/fields it need to read to access the information.

So in your case, it should be something like `price = get.Required.At [ "profile"; "price" ] Decode.float`

[REPL demo](https://fable.io/repl/#?code=LYewJgrgNgpgBAFQBYgC5IHQCUCGA7MEYAVQGcYAnAKCoAoAqeqgZWByijhwAduoBLAMY5U-EHjikUAd354A5nBlxUIOBHIAuKgFpEKdBgBSpcXFpJUqbqU0B6O2wUwobAB79gMDPP7oIAEYYYnbIaEh2AFameHYAbgDMGJbAUACUunAAChRE-ORcBHAAYjCogkhwAIJZAJKkVPQZVCDcMBLMAJ6kqDDALW0SxTgBsBgAwiAUMAPtJSNjWDA4gqizQwveSyuoGDmtDa1zAKKu+UjrcKfA59jLq5dhhibiNLCocNFmALxUcP9wABEwKoAG8-kDSJ1gAEQFBAXBNECAPJYcYAGUBABoIYDuLkAGb8WAIpHggFA-FCGCkuAAVgATBgAJwADhxFMBATKOFpgIAjBgAAysxkAFn52Ih-0BcThVTi8j5-IA7My6WK6UKAGxSznAADWqHGPGVzIZjOZCQZQttQuFQr1AMBUBwPQAIvw4nz7czdRznRR8PIaYigWKmWKdBqMNq6U6ZRVgzBSLT7UKA4mkMnSFlKIJ2qgcCG+bR00KAKRpBNAwREbj4ToAORwXj5yKDglgcEmFG4UxEYjwNcBMDcSecfKbMGkcAAmlMDXBmKpBEvjuPs5PM0C5JAehROnyqrwBMJRGZmCACahpDhpiPpDAAqQ-KGkYDLNZ7HZpH+MAOXbeHWwAjmAKaCBQ-DcBew5hoCHYrN2vbcHA+RcHAIHcBAvQUJI163ve8BYY2GBwLUHzkBwpBwIWlBUgUcgElMbCwSoMAVHgcIgPInT4VAOFDqQWJoXgXYQGAciKGAIgjG6KYiTcYBgLAd7TCJPB8EIg7iMJhRgEo95gGp3j6PAkzAA2eB8VSbBQVAfHXgSlA0aYN4mXAZ7tOQemkBAvBTKgGlFGwci9Hg+AFpIlBxNSNHSFMUDGfw4EYCOBYgHyACy95LgAamRAASEAUAZdjLjgBJBtUMk9iIABeI7kKsUx8ggHFIFxUA8UeO6Ap4xbvkCX42D+RIRWJ-DsKA4ECAo+IwNwGAgXYA0hqQOjTtIOiRNw8h2KiGIYLtSoQgAvlQF2ciCVCoJ0bTLquBoAIoQGg8DfHA0pwOSFIAlCMJwmGB5Sd9FJUgWSIEt1IjfVdALfT0g6CHAXgwpQcDuhx4AY0iWN1uBFAADwriAa6ve9AB8cC-H9AL4zjAEBJEHFrHTdO0ASEASCGHw6NTYPsxSv1C6LkjQrCnCfbzdwAI4QPw0xgBgxT8C4BmAgDksIgzqUgwogti+DUFRdLZRywrSsYFUHwANqUoSxI0gA3A71IIgAupj2OpdDICw0bf3w2LzTvHA0w0Z9uveNzpCVTAxS5MAK5QQoj1ky9b29Bg0d4V8eA0FSeCoASEiAhWVQIhHQA&html=DwCwLgtgNgfAUAAlAUwIYBN4O0iyyoLhgAOAtMgI4CuAlgG4C8A5AMID2AdmMt2QCoBPEsmYIAxlx7cWPAB5gA9OGgBuCSFQAnAM75G1MADMyADmZYcwHeK20SYBDq3jGAIgD6HgBIB5AMr8XopQtABGOopaaOJgAHQkWuzo1LG0XHEQtJxxAFY6bjDAijZ2DpbY1rb2js6unj4BQR4h4ZHRqLFk6OwQCUkpaRlZOfmFxaU1FUihnADWCNFQ7jpgglDIOiDI+G5E0UbuXn6BwaERiuI6kWHUUBComdlxVwUIitPAswtLK2sbWx2YD2IAOR0apxa50ir0UqCgUCeOVeew+cGK2wwWGAYWSggkUFQ13cqBI5Ek3FQ2WQWkKiCs6AYCFo6HcyHutC2ZFJJD24kJxLc7KyXJ540UjPo8GKuPQgmxykgsCAA&css=HQYwhgTgJsCWDOBaMA3MAXSACLBvAUDjgLZgAeiA7rFOgBYBcWAzAKwAMADmQNyFGkIAc1gA7JmACu6APZ8AvoVCQYCZGkwQsy6IlikhAUzz8cUBJwA2YAJ5MAZpcO9TWAFaT46WPZuIQMqLohkFMICHBEHxEWGCWsEKiesHE8GERhlGunGBQ5qJCTABMrNxY7OUKQA)

**Comment by gsscoder** [comment]
This is more than I expected, thank you!
It's important to know, now I'm free to use a automatic mapping or declarative.

I used your library in a (for now) [toy project](https://github.com/gsscoder/quote.fs). Since I think it deserve *more popularity* I've added credits in `README.md` and talked about it on *twitter*.
