### ISSUE TITLE
Discriminated Unions get encoded but fail silently when decoding

### ISSUE THREAD

**Issue by TillRauch** [thoth-org/Thoth.Json#58]
To illustrate the problem I assume some simple types:

```fs
type AlternateString = AlternateString of string

type Basic = {
    Foo: AlternateString
}
```

When encoding this in the backend, everything works fine:
```fs
let basic = { Foo = AlternateString "MyAlternateString" }

let encoded = Encode.Auto.toString(0, basic)

printfn "%s" (encoded.ToString()) // -> "{"Foo":["AlternateString","MyAlternateString"]}"
```

Now when trying to decode the same string in the frontend I run into trouble:
```fs
let encoded = """{"Foo":["AnternateString","MyAlternateString"]}"""

let basicDecoded: Result<Basic, string> = Decode.Auto.fromString<Basic>(encoded)
```
After the last line subsequent lines don't seem to be executed, simple debug messages after that don't even work.

Am I missing something or doing something wrong or is this a genuine issue?

**Comment by MangelMaxime** [comment]
Hello,

Which version of the library are you using? Which version of Fable?

I am not sure to understand what you mean by fail silently. The string you are providing in the tired snippet is not a valid representation of the `AlternateString` DU.

You wrote `AnternateString` instead of `AlternateString` with a `L` as the second letter.

You are also using the safe version of the decoder so it's will not throw an exception it just return 

```
Error at: `$.Foo`
I run into a `fail` decoder: Cannot find case AnternateString in Test.AlternateString
```

wrapped of `Result.Error`.

[Demo in the REPL](https://fable.io/repl/#?code=PYBwpgdgBAKgFsALnAdAKQM7AgKFJKAMQEMAjAGzBQGFgAnMHHRAT3CgEFzEw6JieAZUR0AlhADmUALyduvfkJHipwAGZQMyyU1bsAQsQyiAxjKgBvHFBtFgwAFxyefAWGFidAXyaVEUUiNTcws7YHMuF0V3bSkAIgBZFkiFNw8VOKgfHD8oSBNgABMwQvMAUQgC4pQOAFdEYBQG9MkACgAGABoAoJMASl8wf3yikoAmczipizjCeziHAG04jggotNi4zsTk+VclTwk4gF0vKbjB-0DjEwARMCqSpwAlMAxa7gAeQxvurUOAHzme6PGr1RpqOjAAC2LQk316ANaI2KhQGuWuphBo0KYxebw+iARv00sSBsmx1TqDRQkJhcOJpiRKPGAxwIE8iDU0DiAFIOJlMXcHjj2ZzuVA+QKejdKeMgA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADiaZs2sZprEwGbZrEMARAH03ACQDyAZT4eClA0AEbaCpooYmAAdMSabKhU0TScMRA0HDEAVtouMMAKVjZ2FsDFtvaOzu5efgFuQaHhkcjRpKhsEHEJSSlpGVm5+YUVpQhKKOgIIYkC4lDI2tquyMRkElzImYia+XBYWMCo9Bg0qK6IUBnaIKRrxC4LSysuVzd3DyMKJ3TwhbNUAJ-kpILAgA&css=HQYwhgNiCuFgLgewE4AIDeAoVPUHcBLAE3gAsAuVAFgAYB2ABwA8BubXAIxSIFNlKATM1Qc4IANaoAzogjE2uEdz4BaZGCIFoUygEYArMwW4GGzQDsA5nppHMAX0xPQkGHCTIVHaPCTmM7DikPASWpPCUtHaKpkQW1qgG0bjwPEzwKpCh5pQgPOapyMY4ALZgyJYEOaiGrIGoAG588ATgEJlyltUlxEQQPMX4xGSU+rWDAGaIBSpSBABePIJUyThy5jwqwaHhkbZ1ijDIMvyoDIhVhYNcTLOkGoh4lDSoLwDMwqJgEmyOmC5QWAIFBeHx+YAEKQqTSVeABRQcb7iSzIRDQcxEFQgWQoSidcIonj5X7ONpuYGeby+aYQqGIBjwzhIlFojFYnGnfHwUTQAYOIA)

**Comment by TillRauch** [comment]
Hi,

That Typo was my fault and only in the examples I wrote on GitHub, sorry about that.

Versions I am using:

- Thoth.Json - 3.5

- Fable - 3.0.0

By failing silently I mean that in this example:
```
printfn "Debug1"
let basicDecoded: Result<Basic, string> = Decode.Auto.fromString<Basic>(encoded)
printfn "Debug2"
```
only `Debug1` will be printed out. The `Debug2` and any other Code after that doesn't seem to be executed.

At this point I suspect some conflict between other Libraries I am using, I will keep you updated if I find out what caused the Issue.

**Comment by MangelMaxime** [comment]
Ok, please make sure you are using the latest version of all the deps npm and nuget ones.

Because, your use case is basic, and I suspect a lot of people are using it like that :).

If you have a reproduction repo it can also allow me to help you.

**Comment by TillRauch** [comment]
I found the issue:
I was still using an old Fable.Core version (3.0.0). Updating to 3.1.4 fixed the issue.

Thanks :)
